[package]
name = "author"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4", features = ["openssl"] }
chrono = { version ="0.4.22", features= ["serde"] }
dotenv = "0.15"
diesel = { version = "1.4.4", features = ["postgres", "uuidv07", "r2d2", "chrono"] }
openssl = "0.10"
r2d2 = "0.8.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
structopt = "0.3"
uuid = { version = "0.7", features = ["serde", "v4"] }
jsonwebtokens = "1.1.0"
regex = "1.8.1"
