-- Your SQL goes here
ALTER TABLE users ADD COLUMN updated_at TIMESTAMP DEFAULT NOW();
ALTER TABLE prompts ADD COLUMN updated_at TIMESTAMP DEFAULT NOW();
ALTER TABLE topups ADD COLUMN updated_at TIMESTAMP DEFAULT NOW();
ALTER TABLE subscriptions ADD COLUMN updated_at TIMESTAMP DEFAULT NOW();