name: Build pipleine

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    name: Rust Authentication project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install libssl
        run: sudo apt install -y libssl-dev

      - name: Install Diesel CLI
        run: cargo install diesel_cli --no-default-features --features postgres

      - name: Build
        run: cargo build --release --all-features

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Create env file
        run: |
          echo "HOST=${{ secrets.HOST }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "BEARER_TOKEN=${{ secrets.BEARER_TOKEN }}" >> .env

      - name: Build and tag Docker image
        uses: docker/build-push-action@v2
        with:
          env_file: .env
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/author:latest
